- id: file-name-checker
  name: File Name Checker
  entry: file-name-checker
  language: python
  files: "^.*$"

- id: node-name-checker
  name: Node Name Checker
  entry: node-name-checker
  language: python
  files: '\.tscn$'

- id: signal-connection-checker
  name: Signal Connection Checker
  entry: signal-connection-checker
  language: python
  files: '\.tscn$'

- id: node-order-checker
  name: Node Order Checker
  entry: node-order-checker
  language: python
  files: '\.tscn$'

- id: node-path-checker
  name: Node Path Checker
  entry: node-path-checker
  language: python
  files: '\.tscn$'
