from pathlib import Path
import os
import re
import sys

node_order = {
    "Node": [
        "Node",
        "MissingNode",
        "InstancePlaceholder",
        "Viewport",
        "SubViewport",
        "HTTPRequest",
        "Timer",
        "CanvasLayer",
        "ResourcePreloader",
        "Window",
        "StatusIndicator",
        "Popup",
        "PopupPanel",
        "AcceptDialog",
        "ConfirmationDialog",
        "FileDialog",
        "PopupMenu",
        "AnimationMixer",
        "AnimationPlayer",
        "AnimationTree",
        "ShaderGlobalsOverride",
        "WorldEnvironment",
        "NavigationAgent3D",
        "ParallaxBackground",
        "AudioStreamPlayer",
        "NavigationAgent2D",
        "MultiplayerSpawner",
        "MultiplayerSynchronizer",
        "EditorPlugin",
        "EditorFileDialog",
        "EditorResourcePreview",
        "EditorFileSystem",
        "ScriptCreateDialog",
        "EditorCommandPalette",
        "GridMapEditorPlugin",
    ],
    "CanvasItem": [
        "CanvasItem",
        "Node2D",
        "CanvasModulate",
        "Control",
        "BaseButton",
        "Button",
        "Label",
        "Range",
        "ScrollBar",
        "HScrollBar",
        "VScrollBar",
        "ProgressBar",
        "Slider",
        "HSlider",
        "VSlider",
        "CheckBox",
        "CheckButton",
        "LinkButton",
        "Panel",
        "TextureRect",
        "ColorRect",
        "NinePatchRect",
        "ReferenceRect",
        "Container",
        "AspectRatioContainer",
        "TabContainer",
        "TabBar",
        "Separator",
        "HSeparator",
        "VSeparator",
        "TextureButton",
        "BoxContainer",
        "HBoxContainer",
        "VBoxContainer",
        "GridContainer",
        "CenterContainer",
        "ScrollContainer",
        "PanelContainer",
        "FlowContainer",
        "HFlowContainer",
        "VFlowContainer",
        "MarginContainer",
        "TextureProgressBar",
        "ItemList",
        "LineEdit",
        "VideoStreamPlayer",
        "Tree",
        "TextEdit",
        "CodeEdit",
        "MenuBar",
        "MenuButton",
        "OptionButton",
        "SpinBox",
        "ColorPicker",
        "ColorPickerButton",
        "RichTextLabel",
        "SubViewportContainer",
        "SplitContainer",
        "HSplitContainer",
        "VSplitContainer",
        "GraphElement",
        "GraphNode",
        "GraphFrame",
        "GraphEdit",
        "FoldableContainer",
        "CanvasGroup",
        "CPUParticles2D",
        "GPUParticles2D",
        "Sprite2D",
        "AnimatedSprite2D",
        "Marker2D",
        "Line2D",
        "MeshInstance2D",
        "MultiMeshInstance2D",
        "CollisionObject2D",
        "PhysicsBody2D",
        "StaticBody2D",
        "AnimatableBody2D",
        "RigidBody2D",
        "CharacterBody2D",
        "Area2D",
        "CollisionShape2D",
        "CollisionPolygon2D",
        "RayCast2D",
        "ShapeCast2D",
        "VisibleOnScreenNotifier2D",
        "VisibleOnScreenEnabler2D",
        "Polygon2D",
        "Skeleton2D",
        "Bone2D",
        "Light2D",
        "PointLight2D",
        "DirectionalLight2D",
        "LightOccluder2D",
        "BackBufferCopy",
        "Camera2D",
        "AudioListener2D",
        "Joint2D",
        "PinJoint2D",
        "GrooveJoint2D",
        "DampedSpringJoint2D",
        "TouchScreenButton",
        "TileMapLayer",
        "Parallax2D",
        "RemoteTransform2D",
        "ParallaxLayer",
        "TileMap",
        "PhysicalBone2D",
        "AudioStreamPlayer2D",
        "Path2D",
        "PathFollow2D",
        "NavigationRegion2D",
        "NavigationObstacle2D",
        "NavigationLink2D",
        "EditorToaster",
        "ScriptEditor",
        "ScriptEditorBase",
        "EditorInspector",
        "EditorProperty",
        "EditorSpinSlider",
        "EditorResourcePicker",
        "EditorScriptPicker",
        "FileSystemDock",
        "OpenXRInteractionProfileEditorBase",
        "OpenXRInteractionProfileEditor",
        "OpenXRBindingModifierEditor",
    ],
    "Node3D": [
        "Node3D",
        "Skeleton3D",
        "ImporterMeshInstance3D",
        "VisualInstance3D",
        "GeometryInstance3D",
        "Camera3D",
        "AudioListener3D",
        "XRCamera3D",
        "XRNode3D",
        "XRController3D",
        "XRAnchor3D",
        "XROrigin3D",
        "SkeletonModifier3D",
        "XRBodyModifier3D",
        "XRHandModifier3D",
        "XRFaceModifier3D",
        "MeshInstance3D",
        "OccluderInstance3D",
        "SpriteBase3D",
        "Sprite3D",
        "AnimatedSprite3D",
        "Label3D",
        "Light3D",
        "DirectionalLight3D",
        "OmniLight3D",
        "SpotLight3D",
        "ReflectionProbe",
        "Decal",
        "VoxelGI",
        "LightmapGI",
        "LightmapProbe",
        "GPUParticles3D",
        "GPUParticlesCollision3D",
        "GPUParticlesCollisionBox3D",
        "GPUParticlesCollisionSphere3D",
        "GPUParticlesCollisionSDF3D",
        "GPUParticlesCollisionHeightField3D",
        "GPUParticlesAttractor3D",
        "GPUParticlesAttractorBox3D",
        "GPUParticlesAttractorSphere3D",
        "GPUParticlesAttractorVectorField3D",
        "CPUParticles3D",
        "Marker3D",
        "ModifierBoneTarget3D",
        "RootMotionView",
        "RetargetModifier3D",
        "SpringBoneSimulator3D",
        "SpringBoneCollision3D",
        "SpringBoneCollisionSphere3D",
        "SpringBoneCollisionCapsule3D",
        "SpringBoneCollisionPlane3D",
        "BoneConstraint3D",
        "CopyTransformModifier3D",
        "ConvertTransformModifier3D",
        "AimModifier3D",
        "CollisionObject3D",
        "PhysicsBody3D",
        "StaticBody3D",
        "AnimatableBody3D",
        "RigidBody3D",
        "CharacterBody3D",
        "SpringArm3D",
        "PhysicalBoneSimulator3D",
        "PhysicalBone3D",
        "SoftBody3D",
        "BoneAttachment3D",
        "LookAtModifier3D",
        "SkeletonIK3D",
        "VehicleBody3D",
        "VehicleWheel3D",
        "Area3D",
        "CollisionShape3D",
        "CollisionPolygon3D",
        "RayCast3D",
        "ShapeCast3D",
        "MultiMeshInstance3D",
        "Path3D",
        "PathFollow3D",
        "VisibleOnScreenNotifier3D",
        "VisibleOnScreenEnabler3D",
        "FogVolume",
        "RemoteTransform3D",
        "Joint3D",
        "PinJoint3D",
        "HingeJoint3D",
        "SliderJoint3D",
        "ConeTwistJoint3D",
        "Generic6DOFJoint3D",
        "NavigationRegion3D",
        "NavigationObstacle3D",
        "NavigationLink3D",
        "AudioStreamPlayer3D",
        "CSGShape3D",
        "CSGPrimitive3D",
        "CSGMesh3D",
        "CSGSphere3D",
        "CSGBox3D",
        "CSGCylinder3D",
        "CSGTorus3D",
        "CSGPolygon3D",
        "CSGCombiner3D",
        "GridMap",
        "OpenXRCompositionLayer",
        "OpenXRCompositionLayerEquirect",
        "OpenXRCompositionLayerCylinder",
        "OpenXRCompositionLayerQuad",
        "OpenXRHand",
        "OpenXRVisibilityMask",
    ],
}
{
    "Node": [
        "MissingNode",
        "InstancePlaceholder",
        "Viewport",
        "SubViewport",
        "HTTPRequest",
        "Timer",
        "CanvasLayer",
        "ResourcePreloader",
        "Window",
        "StatusIndicator",
        "Popup",
        "PopupPanel",
        "AcceptDialog",
        "ConfirmationDialog",
        "FileDialog",
        "PopupMenu",
        "AnimationMixer",
        "AnimationPlayer",
        "AnimationTree",
        "ShaderGlobalsOverride",
        "WorldEnvironment",
        "NavigationAgent3D",
        "ParallaxBackground",
        "AudioStreamPlayer",
        "NavigationAgent2D",
        "MultiplayerSpawner",
        "MultiplayerSynchronizer",
        "EditorPlugin",
        "EditorFileDialog",
        "EditorResourcePreview",
        "EditorFileSystem",
        "ScriptCreateDialog",
        "EditorCommandPalette",
        "GridMapEditorPlugin",
    ],
    "CanvasItem": [
        "CanvasItem",
        "Node2D",
        "CanvasModulate",
        "Control",
        "BaseButton",
        "Button",
        "Label",
        "Range",
        "ScrollBar",
        "HScrollBar",
        "VScrollBar",
        "ProgressBar",
        "Slider",
        "HSlider",
        "VSlider",
        "CheckBox",
        "CheckButton",
        "LinkButton",
        "Panel",
        "TextureRect",
        "ColorRect",
        "NinePatchRect",
        "ReferenceRect",
        "Container",
        "AspectRatioContainer",
        "TabContainer",
        "TabBar",
        "Separator",
        "HSeparator",
        "VSeparator",
        "TextureButton",
        "BoxContainer",
        "HBoxContainer",
        "VBoxContainer",
        "GridContainer",
        "CenterContainer",
        "ScrollContainer",
        "PanelContainer",
        "FlowContainer",
        "HFlowContainer",
        "VFlowContainer",
        "MarginContainer",
        "TextureProgressBar",
        "ItemList",
        "LineEdit",
        "VideoStreamPlayer",
        "Tree",
        "TextEdit",
        "CodeEdit",
        "MenuBar",
        "MenuButton",
        "OptionButton",
        "SpinBox",
        "ColorPicker",
        "ColorPickerButton",
        "RichTextLabel",
        "SubViewportContainer",
        "SplitContainer",
        "HSplitContainer",
        "VSplitContainer",
        "GraphElement",
        "GraphNode",
        "GraphFrame",
        "GraphEdit",
        "FoldableContainer",
        "CanvasGroup",
        "CPUParticles2D",
        "GPUParticles2D",
        "Sprite2D",
        "AnimatedSprite2D",
        "Marker2D",
        "Line2D",
        "MeshInstance2D",
        "MultiMeshInstance2D",
        "CollisionObject2D",
        "PhysicsBody2D",
        "StaticBody2D",
        "AnimatableBody2D",
        "RigidBody2D",
        "CharacterBody2D",
        "Area2D",
        "CollisionShape2D",
        "CollisionPolygon2D",
        "RayCast2D",
        "ShapeCast2D",
        "VisibleOnScreenNotifier2D",
        "VisibleOnScreenEnabler2D",
        "Polygon2D",
        "Skeleton2D",
        "Bone2D",
        "Light2D",
        "PointLight2D",
        "DirectionalLight2D",
        "LightOccluder2D",
        "BackBufferCopy",
        "Camera2D",
        "AudioListener2D",
        "Joint2D",
        "PinJoint2D",
        "GrooveJoint2D",
        "DampedSpringJoint2D",
        "TouchScreenButton",
        "TileMapLayer",
        "Parallax2D",
        "RemoteTransform2D",
        "ParallaxLayer",
        "TileMap",
        "PhysicalBone2D",
        "AudioStreamPlayer2D",
        "Path2D",
        "PathFollow2D",
        "NavigationRegion2D",
        "NavigationObstacle2D",
        "NavigationLink2D",
        "EditorToaster",
        "ScriptEditor",
        "ScriptEditorBase",
        "EditorInspector",
        "EditorProperty",
        "EditorSpinSlider",
        "EditorResourcePicker",
        "EditorScriptPicker",
        "FileSystemDock",
        "OpenXRInteractionProfileEditorBase",
        "OpenXRInteractionProfileEditor",
        "OpenXRBindingModifierEditor",
    ],
    "Node3D": [
        "Node3D",
        "Skeleton3D",
        "ImporterMeshInstance3D",
        "VisualInstance3D",
        "GeometryInstance3D",
        "Camera3D",
        "AudioListener3D",
        "XRCamera3D",
        "XRNode3D",
        "XRController3D",
        "XRAnchor3D",
        "XROrigin3D",
        "SkeletonModifier3D",
        "XRBodyModifier3D",
        "XRHandModifier3D",
        "XRFaceModifier3D",
        "MeshInstance3D",
        "OccluderInstance3D",
        "SpriteBase3D",
        "Sprite3D",
        "AnimatedSprite3D",
        "Label3D",
        "Light3D",
        "DirectionalLight3D",
        "OmniLight3D",
        "SpotLight3D",
        "ReflectionProbe",
        "Decal",
        "VoxelGI",
        "LightmapGI",
        "LightmapProbe",
        "GPUParticles3D",
        "GPUParticlesCollision3D",
        "GPUParticlesCollisionBox3D",
        "GPUParticlesCollisionSphere3D",
        "GPUParticlesCollisionSDF3D",
        "GPUParticlesCollisionHeightField3D",
        "GPUParticlesAttractor3D",
        "GPUParticlesAttractorBox3D",
        "GPUParticlesAttractorSphere3D",
        "GPUParticlesAttractorVectorField3D",
        "CPUParticles3D",
        "Marker3D",
        "ModifierBoneTarget3D",
        "RootMotionView",
        "RetargetModifier3D",
        "SpringBoneSimulator3D",
        "SpringBoneCollision3D",
        "SpringBoneCollisionSphere3D",
        "SpringBoneCollisionCapsule3D",
        "SpringBoneCollisionPlane3D",
        "BoneConstraint3D",
        "CopyTransformModifier3D",
        "ConvertTransformModifier3D",
        "AimModifier3D",
        "CollisionObject3D",
        "PhysicsBody3D",
        "StaticBody3D",
        "AnimatableBody3D",
        "RigidBody3D",
        "CharacterBody3D",
        "SpringArm3D",
        "PhysicalBoneSimulator3D",
        "PhysicalBone3D",
        "SoftBody3D",
        "BoneAttachment3D",
        "LookAtModifier3D",
        "SkeletonIK3D",
        "VehicleBody3D",
        "VehicleWheel3D",
        "Area3D",
        "CollisionShape3D",
        "CollisionPolygon3D",
        "RayCast3D",
        "ShapeCast3D",
        "MultiMeshInstance3D",
        "Path3D",
        "PathFollow3D",
        "VisibleOnScreenNotifier3D",
        "VisibleOnScreenEnabler3D",
        "FogVolume",
        "RemoteTransform3D",
        "Joint3D",
        "PinJoint3D",
        "HingeJoint3D",
        "SliderJoint3D",
        "ConeTwistJoint3D",
        "Generic6DOFJoint3D",
        "NavigationRegion3D",
        "NavigationObstacle3D",
        "NavigationLink3D",
        "AudioStreamPlayer3D",
        "CSGShape3D",
        "CSGPrimitive3D",
        "CSGMesh3D",
        "CSGSphere3D",
        "CSGBox3D",
        "CSGCylinder3D",
        "CSGTorus3D",
        "CSGPolygon3D",
        "CSGCombiner3D",
        "GridMap",
        "OpenXRCompositionLayer",
        "OpenXRCompositionLayerEquirect",
        "OpenXRCompositionLayerCylinder",
        "OpenXRCompositionLayerQuad",
        "OpenXRHand",
        "OpenXRVisibilityMask",
    ],
}


category_order = {"Node": 0, "CanvasItem": 1, "Node3D": 2}


node_pattern = re.compile(
    r'^\s*\[node\b.*?type="(?P<type>[^"]+)".*?parent="(?P<parent>[^"]+)"', re.IGNORECASE
)

node_name_pattern = re.compile(r'^\s*\[node\s+name="(?P<name>[^"]+)"', re.IGNORECASE)


def scan_file(path: str) -> dict:
    categories = {}

    with open(path, "r", encoding="utf-8") as file:
        for line in file:
            match = node_pattern.match(line)
            node_name = node_name_pattern.match(line)

            if match:
                if match.group("parent") not in categories:
                    categories[match.group("parent")] = []

                categories[match.group("parent")].append(
                    (node_name.group("name"), get_node_category(match.group("type")))
                )

    return categories


def get_node_category(node_type: str) -> str:
    for parent, types in node_order.items():
        if node_type in types:
            return parent
    return "Node"


def main() -> int:
    root = Path.cwd()
    scenes_with_wrong_order = []

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d != "addons"]
        filenames[:] = [f for f in filenames if f.endswith(".tscn")]

        for file_name in filenames:
            file_path = Path(dirpath) / file_name
            rel = file_path.relative_to(root)

            categories = scan_file(str(file_path))

            for parent, children in categories.items():
                expected_index = 0
                for child in children:
                    index = category_order.get(child[1])

                    if index < expected_index:
                        scenes_with_wrong_order.append(
                            (str(file_path), parent, child[0])
                        )
                        break
                    expected_index = index

    if scenes_with_wrong_order:
        for file_path, parent, child in scenes_with_wrong_order:
            print(f"{file_path}: Node '{child}' with parent '{parent}' is out of order")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
